name: Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v2

      - name: Web Sitesi Derle
        run: |
          echo "Statik site içerikleri hazırlanıyor."
          # Gerekirse Jekyll/Hugo/React vb. derleme adımları eklenebilir

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web  # Yayınlanacak klasör 